#
# Module manifest for module 'Devolutions.CIEM.Graph'
#
# Generated by: Adam Bertram
#
# Generated on: 2/19/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Devolutions.CIEM.Graph.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = 'e8fef136-36bc-419e-aff4-9769febd57ab'

# Author of this module
Author = 'Adam Bertram'

# Company or vendor of this module
CompanyName = 'Devolutions Inc.'

# Copyright statement for this module
Copyright = '(c) 2026 Devolutions Inc. All rights reserved.'

# Description of the functionality provided by this module
Description = 'CIEM identity-to-resource relationship graph module. Maps Azure RBAC, Entra ID identities, group memberships, service principals, and app roles to compute permission relationships (CAN_READ/WRITE/MANAGE). Pure PowerShell with no external dependencies.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Functions to export from this module - using wildcard to let PSM1's Export-ModuleMember control exports dynamically.
FunctionsToExport = @('*')

# Cmdlets to export from this module
CmdletsToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module.
        Tags = 'Azure','CIEM','Security','Identity','IAM','Graph','Permissions','RBAC','Entra'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Devolutions/Devolutions-CIEM'

        # ReleaseNotes of this module
        ReleaseNotes = '## 0.1.0 - Initial Release
- Graph data model for identity-to-resource relationships
- Node types for Entra ID identities and Azure RBAC entities
- Edge types for structural and computed permission relationships
- Graph traversal and query methods
- PSU cache serialization/deserialization support
- Permission relationship mappings for Azure resource types'

    } # End of PSData hashtable

 } # End of PrivateData hashtable

}
