#
# Module manifest for module 'Devolutions.CIEM.Manager'
#
# Generated by: Adam Bertram
#
# Generated on: 2/17/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Devolutions.CIEM.Manager.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = 'b7e3a1f4-9c2d-4e8b-a6f1-3d5e7c9b2a4f'

# Author of this module
Author = 'Adam Bertram'

# Company or vendor of this module
CompanyName = 'Devolutions Inc.'

# Copyright statement for this module
Copyright = '(c) 2026 Devolutions Inc. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Management tools for Devolutions CIEM module development. Provides Prowler check syncing, Azure infrastructure provisioning, and check management utilities. Not required for PSU app runtime.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Devolutions.CIEM')

# Functions to export from this module - using wildcard to let PSM1's Export-ModuleMember control exports dynamically.
FunctionsToExport = @('*')

# Cmdlets to export from this module
CmdletsToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# List of all files packaged with this module
FileList = 'Devolutions.CIEM.Manager.psd1', 'Devolutions.CIEM.Manager.psm1',
               'Private/Compare-ProwlerCheck.ps1',
               'Private/Convert-ProwlerCheck.ps1',
               'Private/Get-GitHubRepoTree.ps1',
               'Private/Save-GitHubRepoFile.ps1',
               'Private/Save-GitHubRepoSparseCheckout.ps1',
               'Private/Test-GitRemote.ps1',
               'Public/Get-ProwlerCheck.ps1',
               'Public/New-CIEMAzureManagedIdentity.ps1',
               'Public/New-PSUAzureServicePrincipal.ps1',
               'Public/Remove-CIEMCheck.ps1',
               'Public/Sync-ProwlerCheck.ps1'

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        # Tags applied to this module.
        Tags = 'Azure','CIEM','Security','Identity','IAM','Management','Prowler','PowerShellUniversal'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Devolutions/Devolutions-CIEM'

        # ReleaseNotes of this module
        ReleaseNotes = '## 0.1.0 - Initial Release
- Extracted management functions from Devolutions.CIEM module
- Prowler check sync pipeline (Sync-ProwlerCheck, Get-ProwlerCheck)
- Check management (Remove-CIEMCheck)
- Azure infrastructure provisioning (New-CIEMAzureManagedIdentity, New-PSUAzureServicePrincipal)
- GitHub API helpers for Prowler repository access'

    } # End of PSData hashtable

 } # End of PrivateData hashtable

}
